version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestapp:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules   
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: nestuser
      DATABASE_PASSWORD: nestpass
      DATABASE_NAME: nestdb
    command: npm run start:dev

volumes:
  pgdata:
